apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1-deployment
  labels:
    app: pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
      - name: pod1
        image: pranavpawar3/pod1-image
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: service-url
        - name: WAIT_TIME
          valueFrom:
            configMapKeyRef:
              name: config
              key: time
